### ISSUE TITLE
Labels for all endpoints

### ISSUE THREAD

**Issue by lvaudor** [lvaudor/glitter#120]
Should we consider adding labels for other endpoints than Wikidata with pattern "xxx rdfs: xxxLabel@en (for instance if labels in english)? 
We'd have to check how generic the rdfs:label property is across endpoints... In case it is not that generic, maybe add a column in table "usual_endpoints" to indicate the property name?

**Comment by maelle** [comment]
good idea to let users indicate the property name (in `spq_init()` maybe, and also in `spq_label()`).
