### ISSUE TITLE
clean_wikidata_table() should go

### ISSUE THREAD

**Issue by lvaudor** [lvaudor/glitter#158]
It's not relevant if we consider that glitter is not focused solely on Wikidata.

Plus, it actually could be more generic.

For now, it comprises two features:

- it transforms columns formatted as POINT(xxxxx,yyyyy) into lat and lng columns (useful for direct use in leaflet)
- if simplifies Wikidata identifiers comprising "http://www.wikidata.org/entity/" into "wd:"

This second feature could be generalized to other endpoints using the usual_prefixes dataset

**Comment by maelle** [comment]
> if simplifies Wikidata identifiers comprising "http://www.wikidata.org/entity/" into "wd:"

This is tracked in #8
