### ISSUE TITLE
how to best support tweaking of spq_perform() arguments

### ISSUE THREAD

**Issue by maelle** [lvaudor/glitter#165]
I wonder whether the endpoint and request type should actually be arguments of `spq_init()`.

Then an user could create a basic query object at the beginning of a script and use it in all other calls.

An alternative would be to have options as default for `spq_perform(endpoint = getOption("glitter.endpoint", "Wikidata"))` which is something we have for some other `spq_perform()` arguments!

**Comment by lvaudor** [comment]
yes, them being arguments of spq_init() is a very good idea. You're on fire!
