### ISSUE TITLE
Where are the best docs for each of the example endpoints?

### ISSUE THREAD

**Issue by maelle** [lvaudor/glitter#30]

**Comment by lvaudor** [comment]
Haha! Very good question indeed... Depends whether you're looking for docs about their knowledge graphs, their ontology (classes/properties), or if you're looking for queries examples

For Wikidata, the [Wikidata-SPARQL tutorial](https://www.wikidata.org/wiki/Wikidata:SPARQL_tutorial)  has been VERY useful for us (Camille and I) to learn to navigate in the triplestore through SPARQL queries... The exploration of the "knowledge graph" and "ontology" has mainly been through online browsing WIkidata items though.

For DBpedia, I have been struggling a little bit. There seems to be some official doc [here](https://www.dbpedia.org/)  but I was not really able to make anything of it. I mainly resorted to a few random examples of queries found by googling "dbpedia sparql examples"...

**Comment by maelle** [comment]
For instance I'd like to know the officially supported output formats.
