### ISSUE TITLE
Parsing notes

### ISSUE THREAD

**Issue by maelle** [lvaudor/glitter#34]
* with the dbpedia query
```r
  tib = spq_init() %>%
      spq_prefix(prefixes=c(dbo="http://dbpedia.org/ontology")) %>%
      spq_add("?person rdfs:label 'David Bowie'@en") %>%
      spq_add("?person ?p ?o") %>%
      spq_head(300) %>%
      spq_perform("dbpedia.org/sparql")
```

o is sometimes a character, sometimes an integer. So if I parse each result according to type, I can't bind the rows...

In wikidataServiceQueryR it seems the choice has been made to trust the first result. But I don't think it would be correct here.

* with this query

```r
tib=spq_init() %>%
  spq_prefix(prefixes=c(sym="http://symogih.org/ontology/",
                        syr="http://symogih.org/resource/")) %>%  
  spq_add("?s a ?cl") %>% 
  spq_add("?s ?p ?o1") %>% 
  spq_add("?o1 a ?cl1", required=FALSE) %>% 
  spq_group_by(c("?cl","?p","?cl1")) %>% 
  spq_head(n=10) %>% 
  spq_summarise(c("?effectif"="COUNT(*)")) %>% 
  spq_arrange(c("DESC(?effectif)")) %>% 
  spq_perform(endpoint="http://bhp-publi.ish-lyon.cnrs.fr:8888/sparql")
```

not all rows have 4 variables since cl1 is not required. Therefore the first row does not always have the info on all types, so I couldn't use wikidataServiceQueryR approach here.

**Comment by lvaudor** [comment]
Ah yes, with the "?person ?p ?o" triplet we were really unlikely to get a unique type (since all possible properties are returned). I'll have to think about what approach is best here...

**Comment by maelle** [comment]
To be continued as we write more examples. :popcorn:

**Comment by lvaudor** [comment]
I think I have un-understood something here. What do you mean "parse each result according to type"? Don't we get the results as a table? (in which case we make no choice whatsoever about the class of variables?). In case the class varies according to the item, couldn't we consider that the data are (by default), strings? and... How do we get units?

**Comment by maelle** [comment]
I meant

https://github.com/lvaudor/glitter/blob/978f19d34a675416b78ecb73301030f0dbe9425f/R/send_sparql.R#L101

we could do a better job at assigning the right class to each column... if API results are consistent. We err on the side of caution with character.

**Comment by lvaudor** [comment]
I'm not sure it's a problem to consider everything as character if mixed in the case p ?v ?o. Such a query would only be run in a very exploratory phase (to have a grasp of the kind of info we have on a particular item), and I guess we could do that with a WikidataR function (well, if considering Wikidata of course).

If we want to do something better, we should consider the existence of a ?property hasvaluetype ?valuetype triple pattern in the triplestores I guess (??). I don't think there is such a thing for Wikidata (at least I haven't found it). 

I have just found a property that says if the value returned by the property has a potentially changing type or not:
```
library(glitter)
tib=spq_init() %>% 
  spq_add("?prop wdt:P31 wd:Q18616576", .label="?prop") %>% 
  spq_add("?prop wdt:P2668 ?valuetypechange", .label="?valuetypechange") %>% 
  spq_perform()
tib
```
