### ISSUE TITLE
(better?) results for databnf images

### ISSUE THREAD

**Issue by maelle** [lvaudor/glitter#36]
With #27 

``` r
library("glitter")
tib=spq_add(t="?image dcterms:type <http://purl.org/dc/dcmitype/StillImage>") %>%
  spq_head(n=10) %>% 
  spq_perform(e="dataBNF")

knitr::kable(tib)
```

| image                                                  |
|:-------------------------------------------------------|
| <http://data.bnf.fr/ark:/12148/cb38492172n#Expression> |
| <http://data.bnf.fr/ark:/12148/cb38493336k#Expression> |
| <http://data.bnf.fr/ark:/12148/cb38495068v#Expression> |
| <http://data.bnf.fr/ark:/12148/cb38495307g#Expression> |
| <http://data.bnf.fr/ark:/12148/cb384957632#Expression> |
| <http://data.bnf.fr/ark:/12148/cb384960819#Expression> |
| <http://data.bnf.fr/ark:/12148/cb38496454h#Expression> |
| <http://data.bnf.fr/ark:/12148/cb38496478h#Expression> |
| <http://data.bnf.fr/ark:/12148/cb38496839q#Expression> |
| <http://data.bnf.fr/ark:/12148/cb38497766k#Expression> |

<sup>Created on 2022-02-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

vs https://lvaudor.github.io/glitter/articles/glitter_for_dataBNF.html#images-dans-data-bnf-fr

**Comment by lvaudor** [comment]
Well, yeah, it's better now!

**Comment by maelle** [comment]
Super, et comme tu as vu, je peux fermer. :heavy_check_mark:
