### ISSUE TITLE
Simplify/limit strings input for users

### ISSUE THREAD

**Issue by lvaudor** [lvaudor/glitter#4]
For instance:

  spq_filter("lang(?label)='fr'") 

Would there be a way to make the string "lang(?label)='fr'" closer to R syntax?
(e.g. avoid use of embedded quotes, define an R function lang() rather than relying on the SPARQL keyword)

The same questions apply to e.g.
  
  spq_summarise(c("?nbdoc"="count(distinct ?document)"))

**Comment by maelle** [comment]
What about

```r
spq_filter(lang(label) == "fr")
```

**Comment by maelle** [comment]
> Ce serait ptêt ok de transformer les filter directement, enfin je me demande, comme on peut les accumuler.

Ne les rassembler qu'à la fin comme les order_by.

**Comment by maelle** [comment]
Notes
- I think that the DSL should accept both, say, `MEAN()` and `mean()`, i.e. not be case-sensitive.

**Comment by maelle** [comment]
Started a PR with tibbles of correspondance between functions https://github.com/lvaudor/glitter/pull/55

**Comment by maelle** [comment]
"NOT IN" va être un cas particulier parce qu'en gros on veut %IN% après un !...
