### ISSUE TITLE
Printing in a neater way

### ISSUE THREAD

**Issue by maelle** [lvaudor/glitter#42]
In #41 I'm adding a print method but it's very simple. It might be nicer to add some formatting with cli. E.g. put words like "ORDER BY" in bold, put variables in italic.

**Comment by maelle** [comment]
I mean what should

```
SELECT ?city ?cityLabel ?pop
WHERE{

?city wdt:P31 wd:Q515.
?city wdt:P1082 ?pop.

SERVICE wikibase:label { bd:serviceParam wikibase:language "fr".}
}
```

look like ideally?

**Comment by lvaudor** [comment]
Hey! does it include character coloring? If so maybe we could consider the WikidataQueryService way of doing it?
([See example here](https://query.wikidata.org/#SELECT%20%3Fcity%20%3FcityLabel%20%3Fpop%0AWHERE%7B%0A%0A%3Fcity%20wdt%3AP31%20wd%3AQ515.%0A%3Fcity%20wdt%3AP1082%20%3Fpop.%0A%0ASERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22fr%22.%7D%0A%7D%0ALIMIT%2010))

Else, maybe put (like you suggested) SPARQL keywords in bold and input values in italic:

**SELECT** ?city ?cityLabel ?pop
**WHERE**{

?city _wdt:P31_ _wd:Q515_.
?city _wdt:P1082_ ?pop.

**SERVICE** wikibase:label { bd:serviceParam wikibase:language "fr".}
}
