### ISSUE TITLE
Rm the graph functions?

### ISSUE THREAD

**Issue by maelle** [lvaudor/glitter#48]
I.e. `build_graph_classes()` and `show_graph_classes()`

**Comment by lvaudor** [comment]
Yes, remove! maybe I'll reconsider them for "sequins" package.
+ maybe remove all functions really Wikidata-related such as get_info, get_claim, get_claims, etc.

**Comment by maelle** [comment]
@lvaudor would you make a PR to glitter removing all the graph stuff now that sequins exists?
