### ISSUE TITLE
What to do about && et ||

### ISSUE THREAD

**Issue by maelle** [lvaudor/glitter#57]
In R there is a difference between `||` and `|` (and between `&` and `&&` https://stackoverflow.com/questions/6558921/boolean-operators-and

In SPARQL there is only `||` and `&&`.

What should we accept in the R DSL?

**Comment by maelle** [comment]
@lvaudor what's your opinion?

**Comment by lvaudor** [comment]
ha! just discovered the existence of && and || in R. Seems more interesting to me to just keep & and | though.

**Comment by maelle** [comment]
or should we let users use both versions as it's translated to the same SPARQL thing anyway?

**Comment by lvaudor** [comment]
Indeed we can accomodate for R-users who would use && and || (if there are some ;-) )
