### ISSUE TITLE
Automatically replace R functions/operators with SPARQL keywords

### ISSUE THREAD

**Issue by lvaudor** [lvaudor/glitter#6]
Some SPARQL keywords or functions are close but not identical to their R counterparts. It could be useful to allow users to use the R functions/operators (which they are familiar to) and then to translate them automatically into SPARQL.

This could be useful for functions spq_filter(), spq_mutate(), spq_summarise().

For instance, 
- among the logical operators
  + in R: &, in SPARQL: &&
  + in R: %in%, in SPARQL: in
  + in R: ==, in SPARQL: =
- among the functions
  + in R: mean(), in SPARQL: avg()
 etc.

An uncurated, un-prioritized list of SPARQL keywords: not exists, bound, lcase, coalesce, datatype, str, now, strafer, lang, uri, contains, replace, regex, group_concat, ...

**Comment by maelle** [comment]
And then the SPARQL keywords would _not_ work, correct?

**Comment by maelle** [comment]
Good examples gallery https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/queries/examples

**Comment by maelle** [comment]
The code currently adds padding around "==". This is probably needed for all keywords.

**Comment by maelle** [comment]
Also important to ignore R comments. This way users could annotate their query. Thinking of this as I see 

```
     IN (
               wd:Q11394,  #Endangered
               wd:Q219127, #critcally endangered
               wd:Q278113  #vulnurable
              )
```

**Comment by maelle** [comment]
Just writing down some notes

```r
p <- parse(
  text = "unit=='wd:Q11573'",
  keep.source = TRUE
  )
getParseData(p)

p <- parse(
  text = "status %in% c('wd:Q11394','wd:Q219127', 'wd:Q278113')"
)
getParseData(p)
```

**Comment by maelle** [comment]
Imaginons que l'on reçoive un code de l'utilisateur·rice. Genre "status%in% c("bla", "blop")".

- D'abord séparer selon les espaces.
- Dans chaque fragment parser comme R. Remplacer les trucs spéciaux comme "==". Donc c'est pas grave ici s'il n'y a pas d'espace autour de %in%.
- Tout recoller ensemble (avec des espaces pour la lisibilité).

**Comment by lvaudor** [comment]
> in dbplyr "You can also use [sql()](https://dbplyr.tidyverse.org/reference/sql.html) to insert a raw sql string." so here one could have `spq()`.

Yes I'd like that a lot. Then we'd assume by default that we're passed an "R code string" unless it's passed through spq() (so no, SPARQL keywords would not work unless wrapped in spq() )

**Comment by maelle** [comment]
https://en.wikibooks.org/wiki/SPARQL/Expressions_and_Functions

**Comment by maelle** [comment]
Also https://www.w3.org/TR/rdf-sparql-query/#SparqlOps
