### ISSUE TITLE
Ok to not include timezone?

### ISSUE THREAD

**Issue by maelle** [lvaudor/glitter#60]
https://www.w3.org/TR/sparql11-query/#func-timezone

I am including tz though

**Comment by maelle** [comment]
@lvaudor ok to only have tz, not timezone?

**Comment by lvaudor** [comment]
I have strictly no experience with timezone/tz matters (actually I don't even know the difference) so, really, I trust your judgement !

**Comment by maelle** [comment]
Worst case scenario, if it's useful an user might come ask for it!
