### ISSUE TITLE
What about FILTER NOT EXISTS

### ISSUE THREAD

**Issue by maelle** [lvaudor/glitter#72]
And FILTER EXISTS?

https://www.w3.org/TR/sparql11-query/#func-filter-exists

As their argument is a pattern that can't be easily simplified (like the input of `spq_add`) I wonder how to handle this.

Maybe `spq_filter(exists(spq("?wdLanguage wdt:P31?/wdt:P279+ wd:Q17376908")))`?

**Comment by lvaudor** [comment]
Yep. Just, we could maybe consider that exists()/not_exists() applies to triplets so that the user does not have to explicitly use spq().

**Comment by maelle** [comment]
Any specific use case for this?

**Comment by lvaudor** [comment]
Nope, I think we can drop this
