### ISSUE TITLE
Simplify URIs in tables through a function

### ISSUE THREAD

**Issue by lvaudor** [lvaudor/glitter#8]
Right now package glitter contains a function clean_wikidata_table() which replaces full Wikidata URIs with abbreviated (or prefixed) versions. We could replace this function with a more generic one (i.e. one that would not only apply to Wikidata ontology) using all prefixes listed in usual_prefixes (and maybe with an optional parameter so that users might add their own abbreviations).

**Comment by lvaudor** [comment]
For now, only for tables from Wikidata can glitter transform long urls into "prefixed" strings. This can be interesting when one wishes to display the table resulting from a query without it being too large or cumbersome to read/scroll horizontally.

Maybe we could extend the list of known prefixes provided by the package, to prefixes from other triplestores (e.g. dbpedia). Hence we would offer a function that would not be "clean_wikidata_table()" but "clean_table()" (or, to be more specific about what it does, "prefix_data()").

Hope it's a bit clearer that way ? I guess it will appear quite straightforward if you test the function clean_wikidata_table() for a tibble obtained from Wikidata.

**Comment by maelle** [comment]
similar to the ns argument in SPARL if I follow correctly https://github.com/cran/SPARQL/blob/master/R/SPARQL.R

**Comment by maelle** [comment]
Oh je vois usual_prefixes, désolée.

**Comment by maelle** [comment]
Faire les réductions pourrait être une option de spq_perform, genre `spq_perform(blabla, simplify = TRUE)`

**Comment by maelle** [comment]
Et faudrait trouver comment laisser les utilisateurs rajouter des réductions.

**Comment by maelle** [comment]
@lvaudor what's your current opinion on this? Could you write an example glitter code with what you'd expect it'd return?
