### ISSUE TITLE
Pb with some dbpedia queries: StartTag: invalid element name

### ISSUE THREAD

**Issue by lvaudor** [lvaudor/glitter#9]
This query, when limited to a few results (with, e.g. spq_head(10)) works. But running it with a higher limit (for instance 200) causes an error. I suspect it might be due to the encoding of some results but have no clue how to resolve this.

Note that the corresponding SPARQL query, when executed directly in the SPARQL endpoint, runs successfully.

Error : 1: StartTag: invalid element name

  tib=spq_init() %>% 
    spq_prefix(prefixes=c(dbo="http://dbpedia.org/ontology/")) %>% 
    spq_add("?person rdfs:label 'David Bowie'@en")  %>% 
    spq_add("?person ?p ?o") %>%
    spq_head(10) %>% 
    send("https://dbpedia.org/sparql")

**Comment by maelle** [comment]
Reprex with the current glitter version on the default branch

``` r
library("glitter")
#> Le chargement a nécessité le package : SPARQL
#> Le chargement a nécessité le package : XML
#> Le chargement a nécessité le package : RCurl
tib=spq_init() %>%
spq_prefix(prefixes=c(dbo="http://dbpedia.org/ontology")) %>%
spq_add("?person rdfs:label 'David Bowie'@en") %>%
spq_add("?person ?p ?o") %>%
spq_head(3000) %>%
send("dbpedia.org/sparql")
#> Opening and ending tag mismatch: hr line 5 and body
#> Opening and ending tag mismatch: body line 5 and html
#> EndTag: '</' not found
#> Error: 1: Opening and ending tag mismatch: hr line 5 and body
#> 2: Opening and ending tag mismatch: body line 5 and html
#> 3: EndTag: '</' not found
```

<sup>Created on 2022-02-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I'll add this to my PR removing the SPARQL dependency.
