### ISSUE TITLE
spq_summarise or spq_mutate on xxxLabel (Wikidata)

### ISSUE THREAD

**Issue by lvaudor** [lvaudor/glitter#96]
The following query:

```
spq_init() %>% 
  spq_add("?film wdt:P31 wd:Q11424") %>% 
  spq_add("?film wdt:P921 ?subject",.label="?subject") %>% 
  spq_group_by(film) %>% 
  spq_summarise(subjectLabel_concat=str_c(subjectLabel,sep="; ")) %>% 
  spq_head(10) %>% 
  spq_perform()
```

sends back a tibble with **NA-filled subjectLabel_concat column**.

It is the labelling that goes wrong, i.e. it corresponds to this SPARQL query which **does not actually return any ?subjectLabel**

```
SELECT ?film (GROUP_CONCAT(?subjectLabel;SEPARATOR='; ') AS ?subjectLabel_concat)
WHERE{
?film wdt:P31 wd:Q11424.
?film wdt:P921 ?subject.
SERVICE wikibase:label { bd:serviceParam wikibase:language "en".}
}
GROUP BY ?film
LIMIT 10
```

Based on the examples provided in WikiDataQueryService one way around this problem would be to add a line to SERVICE wikibase:label in order to have ?subjectLabel provided as an intermediary result:

```
SELECT ?film (GROUP_CONCAT(?subjectLabel;SEPARATOR="; ") AS ?subjectLabel_concat)
WHERE{
  
  ?film wdt:P31 wd:Q11424.
  ?film wdt:P921 ?subject.
  
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "fr,en".
    ?subject rdfs:label ?subjectLabel}
}
GROUP BY ?film 
LIMIT 10
```

**Comment by maelle** [comment]
- does this happen for other wikidata queries?
- is this something we should add for all wikidata queries?
- does this belong here or in sequins?

**Comment by maelle** [comment]
another question: should the label languages one can accept, be an option?

**Comment by lvaudor** [comment]
- It would probably happen to all queries where a "summarization operation" is carried out on a xxxLabel variable

- We could add this to all Wikidata queries. The SPARQL queries would then look a bit different (i.e. they'd be a bit longer) when built through glitter than directly with SPARQL though (even when no summarization operation on any xxxLabel is involved). On the other hand, it'd be simpler to solve this issue this way. Why not.

- I think it belongs in glitter because I'd like to have the ability to build queries to pass to wikidata with glitter (although sequins will have additional functionalities linked to Wikidata). Maybe sequins will have functionalities linked to all SPARQL endpoints anyway? (not only Wikidata??)

- the label languages is already an option for wikidata through spq_language(). Are you asking if we should implement that for other endpoints? Actually, yes, and maybe more importantly we could maybe implement in glitter the ability to label things easily by enabling the quick (by option .label="xxx") addition of  "?xxx rdfs:label ?xxxLabel" which would be a very generic, endpoint-transverse way to do this??

**Comment by maelle** [comment]
what I mean is that you used "fr, en". I wonder how to choose the language codes to add there.

**Comment by lvaudor** [comment]
See spq_language() to change default language of labels in Wikidata. 
Does Wikidata return the triplet if no Label is provided? to be checked...

**Comment by maelle** [comment]
Interesting example, for it to work I need to BIND more things!

**Comment by maelle** [comment]
With #142 

``` r
library("glitter")
spq_init() %>% 
  spq_add("?film wdt:P31 wd:Q11424") %>% 
  spq_add("?film wdt:P921 ?subject") %>% 
  spq_label(subject, film) %>%
  spq_group_by(film_label, film) %>% 
  spq_summarise(subject_label_concat=str_c(subject_label,sep="; ")) %>% 
  spq_head(10) %>% 
  spq_perform() %>%
  knitr::kable()
```

| film                                    | film_label                  | subject_label_concat                                           |
|:----------------------------------------|:----------------------------|:---------------------------------------------------------------|
| <http://www.wikidata.org/entity/Q26751> | Moon                        | cloning; solitude; artificial intelligence                     |
| <http://www.wikidata.org/entity/Q26801> | The Men I Wanted            | LGBT-related film                                              |
| <http://www.wikidata.org/entity/Q27338> | The People Under the Stairs | gentrification; child abuse; upper class                       |
| <http://www.wikidata.org/entity/Q27343> | Warm Bodies                 | aviation                                                       |
| <http://www.wikidata.org/entity/Q27411> | Scream                      | horror film; revenge; serial murder                            |
| <http://www.wikidata.org/entity/Q27536> | The Hills Have Eyes Part II | serial killer                                                  |
| <http://www.wikidata.org/entity/Q27751> | Gangster Squad              | Los Angeles Police Department; Gangster Squad; organized crime |
| <http://www.wikidata.org/entity/Q28196> | World War Z                 | zombie; epidemic                                               |
| <http://www.wikidata.org/entity/Q28234> | Les Misérables              | oppression; redemption; rivalry; misery; liberty; Christianity |
| <http://www.wikidata.org/entity/Q28289> | Confession of Murder        | serial killer; revenge                                         |

<sup>Created on 2023-07-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by lvaudor** [comment]
Ha, grouping and summarizing is so beautiful <3

**Comment by maelle** [comment]
I enjoy this query (also because I don't enjoy the animal mayors any more :joy: )

**Comment by lvaudor** [comment]
You know them too well by now.
